services:
  - type: web
    name: frontend
    buildCommand: npm run build
    startCommand: npm run start
    env:
      - key: VITE_API_URL
        value: http://localhost:3000/api/v1
      - key: VITE_BACKEND_CHAT
        value: ws://localhost:3000
      - key: VITE_RAZORPAY_API_ID
        value: rzp_test_52pMKUsVhUtk2U
